spring:
  application:
    name: hack-back

  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

server:
  port: 8086


jwt:
  signing-key: ${JWT_SECRET_KEY}
  expiration-date: ${JWT_SECRET_KEY}
